name: Sync to Shehan-and-susan GitHub Pages

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch: # Allows you to manually trigger the workflow from GitHub's UI

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Push to Shehan-and-susan.github.io
        run: |
          git remote add shehan-and-susan https://shehan-and-susan:${{ secrets.TEMP_FORK_PAT }}@github.com/Shehan-and-susan/shehan-and-susan.github.io.git
          git push shehan-and-susan gh-pages:gh-pages --force